"""
services/report_service.py
--------------------------------------------------------------------------
Turns an existing AI analysis (already generated by ai_service.py) into
a complete, structured investment report with Decision Summary.

This file makes NO external API calls of its own -- no Gemini, no
Alpha Vantage. It only takes the analysis dict that routes/research.py
already has and reshapes/labels it into report sections, plus
composes the structured decision summary and conclusion.
--------------------------------------------------------------------------
"""

from datetime import datetime

REQUIRED_ANALYSIS_FIELDS = [
    "summary",
    "financial_assessment",
    "news_sentiment",
    "key_risks",
    "key_opportunities",
    "overall_outlook",
]


class ReportServiceError(Exception):
    """Raised when the given analysis is missing, not a dict, or
    missing one of the fields a report needs to be built from."""


def build_investment_report(company_name, ticker_symbol, analysis):
    """
    Returns a structured dictionary containing all report sections:
      - company_overview, investment_summary, financial_assessment,
        positive_signals, news_sentiment, key_risks, key_risks_list,
        key_opportunities, overall_outlook, conclusion, decision_summary,
        ai_score, recommendation, generated_at

    Raises ReportServiceError if analysis is missing or malformed.
    """
    if not isinstance(analysis, dict):
        raise ReportServiceError("AI analysis was missing or not a valid object.")

    missing = [field for field in REQUIRED_ANALYSIS_FIELDS if not analysis.get(field)]
    if missing:
        raise ReportServiceError(
            f"AI analysis was missing required field(s): {', '.join(missing)}."
        )

    company_overview = (
        f"{company_name} ({ticker_symbol}) is the subject of this investment "
        f"research report. {analysis['summary']}"
    )

    conclusion = (
        f"Considering the current financial position and prevailing news "
        f"sentiment, {ticker_symbol} presents a profile investors should "
        f"weigh against their own risk tolerance and time horizon. "
        f"{analysis['overall_outlook']}"
    )

    # Ensure structured decision summary exists
    decision_summary = analysis.get("decision_summary")
    if not isinstance(decision_summary, dict):
        rec = analysis.get("recommendation") or "Hold"
        r_view = "Positive" if rec == "Buy" else ("Cautious" if rec == "Sell" else "Neutral")
        decision_summary = {
            "research_view": r_view,
            "suggested_action": "Consider for further research" if r_view == "Positive" else "Add to watchlist",
            "confidence_level": "Medium",
            "why_this_view": [
                f"Analysis synthesized for {company_name} based on verified NSE price data.",
                f"Assigned {rec} stance reflecting balance of opportunities and risks.",
            ],
            "what_could_change_view": "Quarterly earnings results and sustained price momentum.",
            "check_next_checklist": [
                "Review latest quarterly audited financial statements",
                "Verify trading volume relative to 30-session average",
                "Compare performance with sector peers",
                "Check corporate action updates on NSE",
            ],
        }

    pos_signals = analysis.get("positive_signals")
    if not isinstance(pos_signals, list):
        pos_signals = []

    key_risks_list = analysis.get("key_risks_list")
    if not isinstance(key_risks_list, list):
        key_risks_list = []

    return {
        "company_overview": company_overview,
        "investment_summary": analysis["summary"],
        "financial_assessment": analysis["financial_assessment"],
        "positive_signals": pos_signals,
        "news_sentiment": analysis["news_sentiment"],
        "key_risks": analysis["key_risks"],
        "key_risks_list": key_risks_list,
        "key_opportunities": analysis["key_opportunities"],
        "overall_outlook": analysis["overall_outlook"],
        "conclusion": conclusion,
        "decision_summary": decision_summary,
        "ai_score": analysis.get("ai_score"),
        "recommendation": analysis.get("recommendation"),
        "is_deterministic": analysis.get("is_deterministic", False),
        "generated_at": datetime.utcnow().isoformat(),
    }
