"""
services/report_service.py
--------------------------------------------------------------------------
Turns an existing Phase 8 AI analysis (already generated by
ai_service.py) into a fuller, structured investment report.

This file makes NO external API calls of its own -- no Gemini, no
Alpha Vantage. It only takes the analysis dict that routes/research.py
already has (from the same _get_analysis_or_error() helper used by
POST .../analyze) and reshapes/labels it into report sections, plus
composes one additional "conclusion" section by combining pieces of
the analysis that already exist. That keeps this service simple,
fast, and free of its own failure modes around network calls or API
keys -- the only way it can fail is if the analysis it's given is
missing or malformed, which is exactly what ReportServiceError below
is for.
--------------------------------------------------------------------------
"""

from datetime import datetime

# The exact fields ai_service.py guarantees on every successful
# analysis dict -- see ai_service.REQUIRED_FIELDS. Duplicated as a
# plain list here (rather than imported) so this file has no import
# dependency on ai_service.py -- it only needs *a* dict shaped like
# this, not the module that produced it.
REQUIRED_ANALYSIS_FIELDS = [
    "summary",
    "financial_assessment",
    "news_sentiment",
    "key_risks",
    "key_opportunities",
    "overall_outlook",
]


class ReportServiceError(Exception):
    """Raised when the given analysis is missing, not a dict, or
    missing one of the fields a report needs to be built from."""


def build_investment_report(company_name, ticker_symbol, analysis):
    """
    Returns a dict with these keys:
        company_overview, investment_summary, financial_assessment,
        news_sentiment, key_risks, key_opportunities, overall_outlook,
        conclusion, generated_at

    Raises ReportServiceError if `analysis` isn't a usable dict --
    callers (routes/research.py) should catch this and translate it
    into a safe HTTP error rather than letting a raw KeyError/TypeError
    escape.
    """
    if not isinstance(analysis, dict):
        raise ReportServiceError("AI analysis was missing or not a valid object.")

    missing = [field for field in REQUIRED_ANALYSIS_FIELDS if not analysis.get(field)]
    if missing:
        raise ReportServiceError(
            f"AI analysis was missing required field(s): {', '.join(missing)}."
        )

    company_overview = (
        f"{company_name} ({ticker_symbol}) is the subject of this investment "
        f"research report. {analysis['summary']}"
    )

    # A short closing section synthesized from pieces of the analysis
    # that already exist -- not a new AI call, just combining what's
    # already been generated into a final take-away.
    conclusion = (
        f"Considering the current financial position and prevailing news "
        f"sentiment, {ticker_symbol} presents a profile investors should "
        f"weigh against their own risk tolerance and time horizon. "
        f"{analysis['overall_outlook']}"
    )

    return {
        "company_overview": company_overview,
        "investment_summary": analysis["summary"],
        "financial_assessment": analysis["financial_assessment"],
        "news_sentiment": analysis["news_sentiment"],
        "key_risks": analysis["key_risks"],
        "key_opportunities": analysis["key_opportunities"],
        "overall_outlook": analysis["overall_outlook"],
        "conclusion": conclusion,
        # Pass through as-is -- may be None if ai_service.py couldn't
        # validate a usable value from Gemini's response. Never
        # defaulted to a fabricated score/recommendation here.
        "ai_score": analysis.get("ai_score"),
        "recommendation": analysis.get("recommendation"),
        "generated_at": datetime.utcnow().isoformat(),
    }
